// Generated by CoffeeScript 1.6.3
(function() {
  var btc, restify, serve;

  restify = require('restify');

  btc = require('btc');

  serve = function() {
    var server;
    server = restify.createServer({
      name: "btc-api",
      version: "0.1.0"
    });
    server.use(restify.acceptParser(server.acceptable));
    server.use(restify.queryParser());
    server.use(restify.bodyParser());
    server.get('/price/:source', function(req, res, next) {
      if (req.params.source === 'all') {
        btc.price(function(err, prices) {
          return res.send(prices);
        });
      } else {
        btc.price(req.params.source, function(err, prices) {
          return res.send(prices);
        });
      }
      return next();
    });
    return server.listen(4000, function() {
      return console.log('%s listening at %s', server.name, server.url);
    });
  };

  exports.serve = serve;

}).call(this);
